config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/nelson', as: 'rails_admin'
  mount Attachinary::Engine => "/attachinary"

  devise_for :users,
    controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'}


  authenticated :user do
    root 'pages#room', as: :authenticated_root
    get '/home', to: 'pages#home', as: :authentificated_home
  end

  scope '(:locale)', locale: /fr/ do #to use i18n | change /fr/ to /fr|es/ to add spanish
    root to: 'pages#home'
    get '/home', to: 'pages#home'
    get 'NovemberIsCoolAgain', to: 'pages#NovemberIsCoolAgain', as: :novemberiscoolagain
  end

  get "/CallMaxime" => redirect("https://calendly.com/maximebdb/packyourskills")
  get "/joinourteam" => redirect("http://www.packyourskills.com/RecruitmentJanuary2019.pdf"), as: :joinus

  ## BLOG
  get "/blog", to: redirect('http://blog.packyourskills.com/')
  # get "/blog" => redirect("https://medium.com/pack-your-skills")

  ## temporary #########
  get 'NovemberIsTheNewCool', to: 'pages#NovemberIsCoolAgain', as: :novemberisthenewcool
  get 'fr/NovemberIsTheNewCool', to: 'pages#NovemberIsCoolAgain'
  get 'AprilIsComing', to: 'pages#NovemberIsCoolAgain', as: :apriliscoming
  #######################

  ## temporary #########
#  get 'NovemberIsTheNewCool', to: 'pages#NovemberIsTheNewCool', as: :novemberisthenewcool
#  get 'fr/NovemberIsTheNewCool', to: 'pages#NovemberIsTheNewCool'
  #######################


  get 'IAmAPacker', to: 'pages#IAmAPacker', as: :iamapacker
  get 'IAmACrew', to: 'pages#IAmACrew', as: :iamacrew

#  get 'IAmAPacker', to: 'pages#NovemberIsTheNewCool', as: :iamapacker
#  get 'IAmACrew', to: 'pages#NovemberIsTheNewCool', as: :iamacrew

  resources :crews, only: [:edit, :update]
  resources :missions, only: [:index, :edit, :update, :new, :show, :create] do
    resources :connections, only: [:new, :create, :edit, :show, :index, :destroy, :update]
  end
  #to change the status of a mission
  get '/missions/:id/validate', to:'missions#validate', as: 'validate_mission'
  get '/missions/:id/suspend', to:'missions#suspend', as: 'suspend_mission'
  get '/missions/:id/close', to:'missions#close', as: 'close_mission'
  get '/missions/:id/cancel', to:'missions#cancel', as: 'cancel_mission'
  #to change the status of a connection
  get '/missions/:mission_id/connections/:id/accept', to:'connections#accept', as: 'accept_connection'
  get '/missions/:mission_id/connections/:id/refuse', to:'connections#refuse', as: 'refuse_connection'
  get '/missions/:mission_id/connections/:id/cancel', to:'connections#cancel', as: 'cancel_connection'
  get '/missions/:mission_id/connections/:id/confirm', to:'connections#confirm', as: 'confirm_connection'
  get '/missions/:mission_id/connections/:id/put_online', to:'connections#put_online', as: 'put_online_connection'
  get '/missions/:mission_id/connections/:id/put_draft', to:'connections#put_draft', as: 'put_draft_connection'
  get '/missions/:mission_id/connections/:id/put_for_admin_validation', to:'connections#put_for_admin_validation', as: 'put_for_admin_validation_connection'

  resources :packers, only: [:edit, :update, :show]


end

app/models/connection.rb
class Connection < ApplicationRecord
  belongs_to :mission
  belongs_to :packer

  validates :motivation, presence: true
  has_attachments :documents, maximum: 3

  def draft?
    self.status == 'draft'
  end

  def online?
    self.status == 'online'
  end

  def put_draft
    self.status = 'draft'
    self.save
  end

  def put_for_admin_validation
    self.status = 'for_admin_validation'
    self.save
  end

  def put_online
    self.status = 'online'
    self.save
  end

  def suspended?
    self.status == 'suspended'
  end

  def accept
    self.status = 'accepted'
    self.save
  end

  def accepted?
    self.status == 'accepted'
  end

  def refuse
    self.status = 'refused'
    self.save
  end

  def refused?
    self.status == 'refused'
  end

  def cancel
    self.status = 'canceled'
    self.save
  end

  def canceled?
    self.status == 'canceled'
  end

  def confirm
    self.status = 'confirmed'
    self.save
    self.mission.validate
  end

  def confirmed?
    self.status == 'confirmed'
  end

end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController

  before_action :set_connection, only: [ :edit, :show, :put_online, :put_for_admin_validation, :put_draft, :update, :accept, :refuse, :confirm, :cancel, :destroy ]
  before_action :set_mission, only: [ :new, :show, :create, :edit, :update, :accept, :refuse, :confirm, :cancel, :destroy ]
  before_action :set_packer, only: [ :show, :destroy ]

  def index
    @connections = policy_scope(Connection)
  end

  def new
    @connection = Connection.new
    authorize @connection
  end

  def create
    @connection = @mission.connections.new(connection_params)
    params[:commit] == 'Send' ? (@connection.status = 'for_admin_validation') : (@connection.status = 'draft')
    authorize @connection
    @connection.save ? (redirect_to authenticated_root_path) : (render :new)
  end

  def show
  end

  def edit
  end

  def update
    case params[:commit]
    when 'Send'
      @connection.status = 'for_admin_validation'
      @connection.update(connection_params) ? (redirect_to authenticated_root_path) : (render :edit)
    when 'Save'
      @connection.status = 'draft'
      @connection.update(connection_params) ? (redirect_to authenticated_root_path) : (render :edit)
    when 'Save and edit my profile'
      @connection.status = 'draft'
      @connection.update(connection_params) ? (redirect_to edit_packer_path(params["connection"]["packer_id"])) : (render :edit)
    end
  end

  def put_online
    @connection.put_online
    redirect_back(fallback_location: authenticated_root_path)
  end

  def put_for_admin_validation
    @connection.put_for_admin_validation
    redirect_back(fallback_location: authenticated_root_path)
  end

  def put_draft
    @connection.put_draft
    redirect_back(fallback_location: authenticated_root_path)
  end

  def accept
    @connection.accept
    redirect_to authenticated_root_path
  end

  def refuse
    @connection.refuse
    redirect_to authenticated_root_path
  end

  def cancel
    @connection.cancel
    redirect_to authenticated_root_path
  end

  def confirm
    @connection.confirm
    redirect_to authenticated_root_path
  end

  def destroy
    @connection.destroy
    redirect_to authenticated_root_path
  end

  private

  def set_connection
    @connection = Connection.find(params[:id])
    authorize @connection
  end

  def set_mission
    @mission = Mission.find(params[:mission_id])
  end

  def set_packer
    @packer = @connection.packer
  end

  def connection_params
    params.require(:connection).permit(:motivation, :status, :packer_id, documents:[])
  end
end

app/helpers/connections_helper.rb
module ConnectionsHelper
end

app/views/connections/_form.html.erb
<div class="connection">
  <section id="banner_connection_edit" class="banner" >
    <div class="banner_content">
      <h1>Application for <%= @mission.crew.name %></h1>
    </div>
  </section>
  <section id="mission_form" class="form">
    <div class="container_form">
      <%= simple_form_for [@mission, @connection] do |a| %>
        <%= a.hidden_field :packer_id, :value => current_user.packer.id %>
        <p>The project will receive your profile, this text and your contact</p>
        <p>You can tell your motivation for that mission but also everything that seems to be important for you to say to that project</p>
        <p>Do not hesitate to express about your skills and experiences valuable for that mission</p>
        <p>Be yourself, they are waiting for you</p>
        <%= a.input :motivation, class:  'text_field', label: false %>
        <p>Do you want to add any documents ? (3 maximum)
        <%= a.input :documents, label: false, as: :attachinary %>

      <% unless @connection.online? %>
        <%= a.submit 'Save', class: "btn" %>
      <% end %>
        <% if current_user.packer.progress == 100 %>
          <%= a.submit 'Send', class: "btn btn-success"  %>
        <% else %>
          <%= a.submit 'Save and edit my profile', class: "btn btn-primary"  %>
          <p class="comment comment_warning">Your profile is <%= current_user.packer.progress %>% full, you need to reach 100% before sending your application</p>
        <% end %>
      <% end %>
    </div>
  </section>
</div>

app/views/connections/edit.html.erb
<%= render 'form' %>

app/views/connections/new.html.erb
<%= render 'form' %>

app/views/connections/show.html.erb
<div id="packer_and_connection_show" class='global_show'>

  <%= render 'packers/packer_profile' %>

  <section id="application_packer_show" class="section">
    <div class='container container_application'>
      <div class='row row_title'>
        <h2><%= t('packer.show.application.motivation') %></h2>
      </div>
      <div class='row row_placeholder'>
        <div class="col-xs-12 motivation_placeholder">
          <p><%= @connection.motivation %></p>
        </div>
        <div class="annexes">
          <% if @connection.documents.size != 0 %>
            <div class="col-xs-12 title">
              <p><u>Attached files</u></p>
            </div>
            <div class="col-xs-12 content">
              <% @connection.documents.each_with_index do |document, index| %>
                <div class="col-xs-12 col-md-4">
                  <p>Document <%= index + 1 %> - <%= link_to "see", "http://res.cloudinary.com/packyourskills/#{document.resource_type}/upload/v#{document.version}/#{document.public_id}#{'.'unless document.format.nil?}#{document.format}"%></p>
                </div>
              <% end %>
            </div>
          <% end %>
          <div class="col-xs-12 title">
            <p><u>Contacts</u></p>
          </div>
          <div class="col-xs-12 content">
            <% unless @connection.packer.website == (nil || "") %>
              <div class="col-xs-12 col-md-6">
                <p><strong>Website</strong>: <%= @connection.packer.website %></p>
              </div>
            <% end %>
            <% unless @connection.packer.cv_link == (nil || "") %>
              <div class="col-xs-12 col-md-6">
                <p><strong>Online CV</strong>: <%= @connection.packer.cv_link %></p>
              </div>
            <% end %>
            <% unless @connection.packer.facebook == (nil || "") %>
              <div class="col-xs-12 col-md-6">
                <p><strong>Facebook</strong>: <%= @connection.packer.facebook %></p>
              </div>
            <% end %>
            <% unless @connection.packer.instagram == (nil || "") %>
              <div class="col-xs-12 col-md-6">
                <p><strong>Instagram</strong>: <%= @connection.packer.instagram %></p>
              </div>
            <% end %>
            <% unless @connection.packer.other_link == (nil || "") %>
              <div class="col-xs-12 col-md-6">
                <p><strong>Other link</strong>: <%= @connection.packer.other_link %></p>
              </div>
            <% end %>
            <% unless @connection.packer.skype == (nil || "") %>
              <div class="col-xs-12 col-md-6">
                <p><strong>Skype</strong>: <%= @connection.packer.skype %></p>
              </div>
            <% end %>
            <% unless @connection.packer.user.email == (nil || "") %>
              <div class="col-xs-12 col-md-6">
                <p><strong>Email</strong>: <%= @connection.packer.user.email %></p>
              </div>
            <% end %>
            <% unless @connection.packer.phone == (nil || "") %>
              <div class="col-xs-12 col-md-6">
                <p><strong>Phone</strong>: <%= @connection.packer.phone %></p>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>
  <% if current_user.role == "admin" %>
    <section id="admin_section" class="section">
      <h2>Admin part</h2>

      <p>Actual status : <%= @connection.status %> </p>
      <p>Change to
      <%= link_to "online",  put_online_connection_path(@connection) %> -
      <%= link_to "draft",  put_draft_connection_path(@connection) %> -
      <%= link_to "for_admin_validation",  put_for_admin_validation_connection_path(@connection) %>
    <!--
      <%= link_to "accept",  accept_connection_path(@mission,@connection) %>
      <%= link_to "refuse",  refuse_connection_path(@mission,@connection) %>
      <%= link_to "cancel",  cancel_connection_path(@mission,@connection) %>
      <%= link_to "confirm",  confirm_connection_path(@mission,@connection) %>
      <%= link_to "delete",  mission_connection_path(@mission,@connection), method: :delete, data: {confirm: "Are your sure?"} %></p>
    -->

    </section>
  <% end %>
</div>