config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/nelson', as: 'rails_admin'
  mount Attachinary::Engine => "/attachinary"

  devise_for :users,
    controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'}


  authenticated :user do
    root 'pages#room', as: :authenticated_root
    get '/home', to: 'pages#home', as: :authentificated_home
  end

  scope '(:locale)', locale: /fr/ do #to use i18n | change /fr/ to /fr|es/ to add spanish
    root to: 'pages#home'
    get '/home', to: 'pages#home'
    get 'NovemberIsCoolAgain', to: 'pages#NovemberIsCoolAgain', as: :novemberiscoolagain
  end

  get "/CallMaxime" => redirect("https://calendly.com/maximebdb/packyourskills")
  get "/joinourteam" => redirect("http://www.packyourskills.com/RecruitmentJanuary2019.pdf"), as: :joinus

  ## BLOG
  get "/blog", to: redirect('http://blog.packyourskills.com/')
  # get "/blog" => redirect("https://medium.com/pack-your-skills")

  ## temporary #########
  get 'NovemberIsTheNewCool', to: 'pages#NovemberIsCoolAgain', as: :novemberisthenewcool
  get 'fr/NovemberIsTheNewCool', to: 'pages#NovemberIsCoolAgain'
  get 'AprilIsComing', to: 'pages#NovemberIsCoolAgain', as: :apriliscoming
  #######################

  ## temporary #########
#  get 'NovemberIsTheNewCool', to: 'pages#NovemberIsTheNewCool', as: :novemberisthenewcool
#  get 'fr/NovemberIsTheNewCool', to: 'pages#NovemberIsTheNewCool'
  #######################


  get 'IAmAPacker', to: 'pages#IAmAPacker', as: :iamapacker
  get 'IAmACrew', to: 'pages#IAmACrew', as: :iamacrew

#  get 'IAmAPacker', to: 'pages#NovemberIsTheNewCool', as: :iamapacker
#  get 'IAmACrew', to: 'pages#NovemberIsTheNewCool', as: :iamacrew

  resources :crews, only: [:edit, :update]
  resources :missions, only: [:index, :edit, :update, :new, :show, :create] do
    resources :connections, only: [:new, :create, :edit, :show, :index, :destroy, :update]
  end
  #to change the status of a mission
  get '/missions/:id/validate', to:'missions#validate', as: 'validate_mission'
  get '/missions/:id/suspend', to:'missions#suspend', as: 'suspend_mission'
  get '/missions/:id/close', to:'missions#close', as: 'close_mission'
  get '/missions/:id/cancel', to:'missions#cancel', as: 'cancel_mission'
  #to change the status of a connection
  get '/missions/:mission_id/connections/:id/accept', to:'connections#accept', as: 'accept_connection'
  get '/missions/:mission_id/connections/:id/refuse', to:'connections#refuse', as: 'refuse_connection'
  get '/missions/:mission_id/connections/:id/cancel', to:'connections#cancel', as: 'cancel_connection'
  get '/missions/:mission_id/connections/:id/confirm', to:'connections#confirm', as: 'confirm_connection'
  get '/missions/:mission_id/connections/:id/put_online', to:'connections#put_online', as: 'put_online_connection'
  get '/missions/:mission_id/connections/:id/put_draft', to:'connections#put_draft', as: 'put_draft_connection'
  get '/missions/:mission_id/connections/:id/put_for_admin_validation', to:'connections#put_for_admin_validation', as: 'put_for_admin_validation_connection'

  resources :packers, only: [:edit, :update, :show]


end

app/views/pages/IAmACrew.html.erb
<div id="iamacrew" class="page_IamA">
  <section class="banner banner_iamacrew" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @banner_url %>')" >
    <div class="banner_content">
      <h1><%= t('iamacrew.title') %></h1>
    </div>
  </section>
  <section class="question_left section section_red_shape_photo_right section_path section_left_path" >
    <div class="container">
      <h2><%= t('iamacrew.q1') %></h2>
      <p><%= t('iamacrew.a1_html') %></p>
      <h2><%= t('iamacrew.q2') %></h2>
      <p><%= t('iamacrew.a2_html') %></p>
    </div>
  </section>
  <section class="question_right section section_yellow1_left" >
    <div class="container">
      <h2><%= t('iamacrew.q3') %></h2>
      <p><%= t('iamacrew.a3_html') %></p>
      <h2><%= t('iamacrew.q4') %></h2>
      <p><%= t('iamacrew.a4_html') %></p>
    </div>
  </section>

  <section class="call2action" >
    <div class="container">
      <h2><%= t('iamacrew.participate') %></h2>
      <p><%= t('iamacrew.next_edition_html') %></p>
      <%= link_to t('iamacrew.call2action'), novemberiscoolagain_path, class: "btn btn-success" %>
    </div>
  </section>
</div>

app/views/pages/IAmAPacker.html.erb
<div id="iamapacker" class="page_IamA">
  <section class="banner banner_iamapacker" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @banner_url %>')" >
    <div class="banner_content">
      <h1><%= t('iamapacker.title') %></h1>
    </div>
  </section>
  <section class="question_left section section_green2_right section_path section_left_path" >
    <div class="container">
      <h2><%= t('iamapacker.q1') %></h2>
      <p><%= t('iamapacker.a1_html') %></p>
      <h2><%= t('iamapacker.q2') %></h2>
      <p><%= t('iamapacker.a2_html') %></p>
    </div>
  </section>
  <section class="question_right section section_blue_shape_photo_left" >
    <div class="container">
      <h2><%= t('iamapacker.q3') %></h2>
      <p><%= t('iamapacker.a3_html') %></p>
      <h2><%= t('iamapacker.q4') %></h2>
      <p><%= t('iamapacker.a4_html') %></p>
    </div>
  </section>
  <% unless signed_in? %>
    <section class="call2action" >
      <div class="container">
        <h2><%= t('iamapacker.participate') %></h2>
        <p><%= t('iamapacker.next_edition') %></p>
        <%= link_to t('iamapacker.call2action'), new_user_registration_path, class: "btn btn-success" %>
      </div>
    </section>
  <% end %>
</div>

app/views/pages/_room_admin.html.erb
<div class="banner">
  <div class="banner_content">
    <h2>Admin</h2>
  </div>
</div>
<h3> Draft Missions </h3>
<% @draft_missions.each_with_index do |mission, index| %>
  <p> -------- </p>
  <p>Mission <%= index + 1 %> - <%= mission.crew.name %> - <%= mission.skill %> - <%= mission.status %> -
    <%= link_to "validate the mission",  validate_mission_path(mission) %><br>
  <%= mission.title %> - <%= link_to "Edit mission info", edit_mission_path(mission.id) %> - <%= link_to "Edit Crew info", edit_crew_path(mission.crew.id) %></p>
  <p>Application</p>
  <% mission.connections.each_with_index do |connection, index| %>
    <p>=><%= index + 1 %> - Status : <%= connection.status %> - Packer : <%= connection.packer.first_name %> <%= connection.packer.last_name %> - <%= link_to "See application", mission_connection_path(mission.id, connection.id) %></p>
  <% end %>
<% end %>
<h3> Online Missions </h3>
<% @public_missions.each_with_index do |mission, index| %>
  <p> -------- </p>
  <p>Mission <%= index + 1 %> - <%= mission.crew.name %> - <%= mission.skill %> - <%= mission.status %> -
    <%= link_to "validate the mission",  validate_mission_path(mission) %><br>
  <%= mission.title %> - <%= link_to "Edit mission info", edit_mission_path(mission.id) %> - <%= link_to "Edit Crew info", edit_crew_path(mission.crew.id) %></p>
  <p>Application</p>
  <% mission.connections.each_with_index do |connection, index| %>
    <p>=><%= index + 1 %> - Status : <%= connection.status %> - Packer : <%= connection.packer.first_name %> <%= connection.packer.last_name %> - <%= link_to "See application", mission_connection_path(mission.id, connection.id) %></p>
  <% end %>
<% end %>
<h3> Validated Missions </h3>
<% @validated_missions.each_with_index do |mission, index| %>
  <p> -------- </p>
  <p>Mission <%= index + 1 %> - <%= mission.crew.name %> - <%= mission.skill %> - <%= mission.status %><br>
  <%= mission.title %> - <%= link_to "Edit mission info", edit_mission_path(mission.id) %> - <%= link_to "Edit Crew info", edit_crew_path(mission.crew.id) %></p>
  <p>Application</p>
  <% mission.connections.each_with_index do |connection, index| %>
    <p>=><%= index + 1 %> - Status : <%= connection.status %> - Packer : <%= connection.packer.first_name %> <%= connection.packer.last_name %> - <%= link_to "See application", mission_connection_path(mission.id, connection.id) %></p>
  <% end %>
<% end %>
<p><%= link_to "Hey Nelson, you have all the power", rails_admin_path %></p>

app/views/pages/_room_crew.html.erb
<div id="room_packer" class="room">

<!-- Banner Part -->
  <section class="banner banner_room">
    <div class="banner_content">
      <h2>Welcome on board</h2>
      <p>We call this page your "room". You can come back here anytime by clicking on the Pack Your Skills logo on top of the page.</p>
      <p>The design isn't crazy here but at least it is functionnal ;)</p>
    </div>
  </section>

  <section class= "SeeMissions">
    <div class="container">
      <h2>Your mission(s)</h2>
      <% @missions.each_with_index do |mission, index| %>
        <div class="row">
          <div class="col-xs-12 col-sm-offset-2 col-sm-8">
            <p><%= link_to mission.title, mission_path(@mission.id) %></p>
            <div class="connections_room_crews">
              <div class="container_flex">
                <div class="box">
                  <% @all_online = mission.connections.select { |c| c.online? } %>
                  <% if @all_online.size == 0 %>
                    <p>no application yet!</p>
                  <% else %>
                    <% if @all_online.size != 0 %>
                      <h2>Applications</h2>
                      <div class="box_application">
                        <% @all_online.each_with_index do |connection, index| %>
                          <p><%= index + 1 %> - <strong><%= connection.packer.first_name %> <%= connection.packer.last_name %></strong> - <%= link_to "view", mission_connection_path(connection.mission.id, connection.id) %></p>
                        <% end %>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </section>
</div>

app/views/pages/_room_packer.html.erb
<div id="room_packer" class="room">

<!-- Banner Part -->
  <section class="banner banner_room" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @banner_url %>')">
    <div class="banner_content">
      <h2>Welcome on board</h2>
      <p>We call this page your "room". You can come back here anytime by clicking on the Pack Your Skills logo on top of the page.</p>
    </div>
  </section>

  <section class= "call2action">
    <div class="container">
      <% unless @packer.progress == 100 %>
        <p>Your profile is <%= @packer.progress %>% full, you need to reach 100% to apply to a mission.</p>
      <% end %>
      <div class="row">
        <div class="col-xs-12 <%= 'col-sm-offset-2' if (@packer.progress <= 50) %> col-sm-4">
          <div class="box">
            <p><%= link_to "Edit your profile", edit_packer_path(current_user.packer.id) %></p>
          </div>
        </div>
        <% unless @packer.progress <= 50 %>
          <div class="col-xs-12 col-sm-4">
            <div class="box">
              <p><%= link_to "See your profile", packer_path(current_user.packer.id) %></p>
            </div>
          </div>
        <% end %>
        <div class="col-xs-12 col-sm-4">
          <div class="box">
            <p><%= link_to "See all missions", missions_path %></p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section id="connections_room_packer">
    <div class="container container_flex">
      <div class="box">
        <h2>Your applications</h2>
        <% if @packer.connections.size == 0 %>
          <p>You don't have any application yet! Don't you wanna come in Paris in April ?</p>
          <p><strong><%= link_to "Discover all the amazing opportunities", missions_path %></strong></p>
        <% else %>
          <% if @all_draft.size != 0 %>
            <div class="box_application">
              <h3> Your draft application(s) </h3>
              <% if @packer.progress == 100 %>
                <p class="comment comment_success">Your profile is full you can now send your application</p>
                <% @all_draft.each_with_index do |connection, index| %>
                  <p><%= index + 1 %> - <strong><%= connection.mission.crew.name %></strong> - <%= link_to "edit and send", edit_mission_connection_path(connection.mission.id, connection.id) %> </p>
                <% end %>
              <% else %>
                <p class="comment comment_warning">Your profile is <%= @packer.progress %>% full, you need to reach 100% before sending your application</p>
                <% @all_draft.each_with_index do |connection, index| %>
                  <p><%= index + 1 %> - <strong><%= connection.mission.crew.name %></strong> - <%= link_to "edit", edit_mission_connection_path(connection.mission.id, connection.id) %> </p>
                <% end %>
              <% end %>
            </div>
          <% end %>

          <% if @all_other.size != 0 %>
            <div class="box_application">
              <h3> Your online application(s) </h3>
              <p class="comment"> Isis or Maxime from Pack Your Skills will come back to you soon</p>
              <% @all_other.each_with_index do |connection, index| %>
                <p><%= index + 1 %> - <strong><%= connection.mission.crew.name %></strong> - <%= link_to "preview", mission_connection_path(connection.mission.id, connection.id) %></p>
              <% end %>
            </div>
          <% end %>

        <% end %>
      </div>
    </div>
  </section>

</div>

app/views/pages/home.html.erb
<div id="home">
  <!-- Banner Part -->
  <section id="home_banner" class="banner section">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-8">
          <h1 class="slogan_part1"><%= t('home.banner.slogan1') %></h1>
          <h1 class="slogan_part1"><%= t('home.banner.slogan2') %> <%= image_tag "/home.can.png", id: 'img_can' %></h1>
          <h1 class="slogan_part2"><%= t('home.banner.slogan3') %></h1>
          <h1 class="slogan_part2"><%= t('home.banner.slogan4') %><%= image_tag "/home.exclamation.png", id: 'home_exclamation'  %></h1>
          <div class="translate"><%= t('home.banner.translate') %></div>
          <h2><%= t('home.banner.baseline1') %></h2>
          <h2><%= t('home.banner.baseline2') %></h2>
        </div>
      </div>
      <div class="row row_call2action">
        <div class="col-xs-12 col-sm-8">
          <%= link_to t('home.banner.call2action'), joinus_path, target: "_blank", :class => "red_call2action"%>
<!--
           <div class="comment_3nd_edition"><%= image_tag "/home.banner.arrowslogan.png" %><%= t('home.banner.message2crews') %></div>
-->
        </div>
      </div>
    </div>
    <div class="footer_banner">
      <a href="#home_mission"><%= image_tag "/home.banner.arrow.png", id: 'arrow_banner'  %></a>
    </div>
  </section>
  <!-- Enf of Banner Part -->

  <!-- Mission Part -->
  <section id="home_mission" class="section section_path section_right_path section_green_yellow_left">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-offset-1 col-sm-8 col-md-offset-2 col-md-7">
          <h1><%= t('home.mission.title') %><span style="color: #D0274D"> PACK YOUR SKILLS</span> ?</h1>
          <p><%= t('home.mission.text1') %></p>
          <p><%= t('home.mission.text2') %></p>
          <p><%= t('home.mission.text3') %></p>
          <p><%= t('home.mission.text4') %></p>
        </div>
        <div class="col-xs-3 col-sm-2 col-md-2 hide_for_phone">
          <%= image_tag "/home.question.png" %>
        </div>
      </div>
    </div>
  </section>
  <!-- Enf of Mission Part -->

  <!-- Benefits Part -->
  <section id="home_benefits" class="section section_path section_left_path section_red1_right">
    <div class='container'>
      <div class='row'>
        <div class='col-xs-12 col-sm-3 hide_for_phone'>
          <%= image_tag "/home.like.png" %>
        </div>
        <div class='col-xs-11 col-sm-9'>
          <h1><%= t('home.benefits.title') %></h1>
          <div class="row">
            <div class='col-xs-12 col-md-4 '>
              <p><strong><%= t('home.benefits.1strong') %></strong></p>
              <p><%= t('home.benefits.1underline') %></p>
            </div>
            <div class='col-xs-12 col-md-4 '>
              <p><strong><%= t('home.benefits.2strong') %></strong></p>
              <p><%= t('home.benefits.2underline') %></p>
            </div>
            <div class='col-xs-12 col-md-4 '>
              <p><strong><%= t('home.benefits.3strong') %></strong></p>
              <p><%= t('home.benefits.3underline') %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- Enf of Benefits Part -->

  <!-- Process Part -->
  <section id="home_process" class="section section_path section_right_path section_blue1_left">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <h1><%= t('home.process.title') %></h1>
        </div>
      </div>
      <div class="row">
        <div class='col-xs-12 col-md-4'>
          <div class='row'>
            <div class='col-xs-4 col-sm-offset-1 col-sm-3 col-md-offset-0   col-md-12'>
              <%= image_tag "/home.process1.png" %>
            </div>
            <div class='col-xs-8 col-sm-6  col-md-12'>
              <p><strong>1.</strong></p>
              <p><%= t('home.process.step1') %></p>
            </div>
          </div>
        </div>
        <div class='col-xs-12 col-md-4'>
          <div class='row'>
            <div class='col-xs-4 col-sm-offset-1 col-sm-3 col-md-offset-0 col-md-12'>
              <%= image_tag "/home.process2.png" %>
            </div>
            <div class='col-xs-8 col-sm-6 col-md-12'>
              <p><strong>2.</strong></p>
              <p><%= t('home.process.step2') %></p>
            </div>
          </div>
        </div>
        <div class='col-xs-12 col-md-4'>
          <div class='row'>
            <div class='col-xs-4 col-sm-offset-1 col-sm-3 col-md-offset-0   col-md-12'>
              <%= image_tag "/home.process3.png" %>
            </div>
            <div class='col-xs-8 col-sm-6  col-md-12'>
              <p><strong>3.</strong></p>
              <p><%= t('home.process.step3') %></p>
            </div>
          </div>
        </div>
      </div>
      <div class="row row_call2action">
        <%= link_to t('home.process.call2action'), missions_path, :class => "red_call2action"%>
      </div>
    </div>
  </section>
  <!-- Enf of Process Part -->

  <!-- Users Part -->
  <section id="home_users" class="section section_path section_left_path">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <h1><%= t('home.users.title') %></h1>
        </div>
      </div>
      <div class="row">
        <div class='col-xs-12 col-md-4'>
          <div class="row">
            <div class='col-xs-12 col-sm-3 col-md-12 hide_for_phone arrow arrow_left'>
              <%= image_tag "/home.packers.png" %>
            </div>
            <div class='col-xd-12 col-sm-9 col-md-12'>
              <p><strong><%= t('home.users.packers.name') %></strong></p>
              <p><%= t('home.users.packers.description') %></p>
              <%= link_to t('home.users.packers.call2action'), iamapacker_path, :class => "white_call2action"%>
            </div>
          </div>
        </div>
        <div class='col-xs-12 col-md-4'>
          <div class="row">
            <div class='col-xs-12 col-sm-3 col-md-12 hide_for_phone arrow arrow_right'>
              <%= image_tag "/home.crews.png" %>
            </div>
            <div class='col-xd-12 col-sm-9 col-md-12'>
              <p><strong><%= t('home.users.crews.name') %></strong></p>
              <p><%= t('home.users.crews.description') %></p>
              <%= link_to t('home.users.crews.call2action'), iamacrew_path, :class => "white_call2action"%>
            </div>
          </div>
        </div>
        <div class='col-xs-12 col-md-4'>
          <div class="row">
            <div class='col-xs-12 col-sm-3 col-md-12 hide_for_phone arrow arrow_right'>
              <%= image_tag "/home.others.png" %>
            </div>
            <div class='col-xd-12 col-sm-9 col-md-12'>
              <p><strong><%= t('home.users.others.name') %></strong></p>
              <p><%= t('home.users.others.description') %></p>
              <a class="white_call2action" href="mailto:hello@packyourskills.com" role="button"><%= t('home.users.others.call2action') %></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- Enf of Users Part -->

  <!-- Testimonies Part -->
  <section id="home_testimonies" class="section section_path section_right_path section_red2_left">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <h1><%= t('home.testimonies.title') %></h1>
        </div>
        <div class='col-xs-12 col-sm-6'>
          <div class='video_testimonies'>
            <iframe src="https://www.youtube.com/embed/videoseries?list=PLTAYKibpcTw9y93AOrDSErsbHcMbbrwDQ" frameborder="0" allowfullscreen></iframe>
          </div>
        </div>
        <div class='col-xs-offset-2 col-xs-10 col-sm-offset-0 col-sm-6'>
          <div class="row text_testimonies">
            <div class='col-xs-6 col-sm-4 hide_for_phone'>
              <%= image_tag "/home.nikol.jpg", class:"img_testmonies hide_for_phone" %>
            </div>
            <div class='col-xs-12 col-sm-8 text_portrait'>
              <p><strong>Nikol Parajova</strong></p>
              <div class="info_portrait hide_for_phone">
                <p>from Slovakia</p>
                <p>Photographer</p>
                <p>Packer @ Jimini's</p>
                <p>March 2017</p>
              </div>
            </div>
          </div>
          <div class='row'>
            <div class='col-xs-12'>
              <p>"Pack your skills gave me one of the best opportunities in my life. I got a chance to experience an amazing social entrepreneurship and spend two wonderful weeks in Paris. If I had a chance to work with pack your skills again I wouldn't doubt for a minute. I met amazing people and made new friends, and I can't be more grateful for it."</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- Enf of Testimonies Part -->

  <!-- Team Part -->
  <section id="home_team" class="section section_green2_right">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-offset-2 col-sm-10">
          <h1><%= t('home.team.title') %></h1>
        </div>
      </div>
      <div class="row team_picture">
        <div class="col-xs-12 col-sm-offset-2 col-sm-6">
          <%= image_tag "/home.team.jpg" %>
        </div>
      </div>
      <div class="row text_team">
        <div class="col-xs-12 col-sm-offset-2 col-sm-5">
          <p><strong>Maxime</strong></p>
          <p><%= t('home.team.maxime') %></p>
        </div>
        <div class="col-xs-12 col-sm-5">
          <p><strong>Isis</strong></p>
          <p><%= t('home.team.isis') %></p>
        </div>
      </div>
    </div>
  </section>
  <!-- Enf of Team Part -->

  <!-- Social Media Part -->
  <section id="home_social_network" class="section section_path section_left_path section_yellow1_left">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-offset-2 col-sm-10">
          <div class="row img_insta">
            <div class="col-xs-4">
              <%= image_tag "/home.insta1.jpg" %>
            </div>
            <div class="col-xs-4">
              <%= image_tag "/home.insta2.jpg" %>
            </div>
            <div class="col-xs-4">
              <%= image_tag "/home.insta3.jpg" %>
            </div>
            <div class="col-xs-4">
              <%= image_tag "/home.insta4.jpg" %>
            </div>
            <div class="col-xs-4">
              <%= image_tag "/home.insta5.jpg" %>
            </div>
            <div class="col-xs-4">
              <%= image_tag "/home.insta6.jpg" %>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-6 col-sm-offset-2 col-sm-3">
          <p><strong><%= t('home.social_network.title') %></strong></p>
        </div>
        <div class="col-xs-1">
          <a href="https://www.instagram.com/packyourskills/" target="_blank" class="logo_social_network logo_insta"></a>
        </div>
        <div class="col-xs-1">
          <a href="https://www.facebook.com/PackYourSkills/" target="_blank" class="logo_social_network logo_fb"></a>
        </div>
        <div class="col-xs-1">
          <a href="https://twitter.com/packyourskills" target="_blank" class="logo_social_network logo_twitter"></a>
        </div>
        <div class="col-xs-1">
          <a href="https://www.youtube.com/playlist?list=PLTAYKibpcTw9u8f5zMHd6su4UrfOO9611" target="_blank" class="logo_social_network logo_youtube"></a>
        </div>
      </div>
    </div>
  </section>
  <!-- Enf of Social Media Part -->

  <!-- Partners Part -->
  <section id="home_partners" class="section">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <h1><%= t('home.partners.title') %></h1>
        </div>
      </div>
      <div class="container_logo">`
        <div class="row">
          <div class="col-xs-4">
            <%= image_tag "/home.logo.partners1.jpg" %>
          </div>
          <div class="col-xs-4">
            <%= image_tag "/home.logo.partners2.jpg" %>
          </div>
          <div class="col-xs-4">
            <%= image_tag "/home.logo.partners3.jpg" %>
          </div>
          <div class="col-xs-4">
            <%= image_tag "/home.logo.partners4.jpg" %>
          </div>
          <div class="col-xs-4">
            <%= image_tag "/home.logo.partners5.jpg" %>
          </div>
          <div class="col-xs-4">
            <%= image_tag "/home.logo.partners6.jpg" %>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- Enf of Partners Part -->
</div>

app/views/pages/room.html.erb
<%= current_user.role == "admin" ? (render 'room_admin') : (current_user.role == "crew" ? (render 'room_crew') : (render 'room_packer')) %>