config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/nelson', as: 'rails_admin'
  mount Attachinary::Engine => "/attachinary"

  devise_for :users,
    controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'}


  authenticated :user do
    root 'pages#room', as: :authenticated_root
    get '/home', to: 'pages#home', as: :authentificated_home
  end

  scope '(:locale)', locale: /fr/ do #to use i18n | change /fr/ to /fr|es/ to add spanish
    root to: 'pages#home'
    get '/home', to: 'pages#home'
    get 'NovemberIsCoolAgain', to: 'pages#NovemberIsCoolAgain', as: :novemberiscoolagain
  end

  get "/CallMaxime" => redirect("https://calendly.com/maximebdb/packyourskills")
  get "/joinourteam" => redirect("http://www.packyourskills.com/RecruitmentJanuary2019.pdf"), as: :joinus

  ## BLOG
  get "/blog", to: redirect('http://blog.packyourskills.com/')
  # get "/blog" => redirect("https://medium.com/pack-your-skills")

  ## temporary #########
  get 'NovemberIsTheNewCool', to: 'pages#NovemberIsCoolAgain', as: :novemberisthenewcool
  get 'fr/NovemberIsTheNewCool', to: 'pages#NovemberIsCoolAgain'
  get 'AprilIsComing', to: 'pages#NovemberIsCoolAgain', as: :apriliscoming
  #######################

  ## temporary #########
#  get 'NovemberIsTheNewCool', to: 'pages#NovemberIsTheNewCool', as: :novemberisthenewcool
#  get 'fr/NovemberIsTheNewCool', to: 'pages#NovemberIsTheNewCool'
  #######################


  get 'IAmAPacker', to: 'pages#IAmAPacker', as: :iamapacker
  get 'IAmACrew', to: 'pages#IAmACrew', as: :iamacrew

#  get 'IAmAPacker', to: 'pages#NovemberIsTheNewCool', as: :iamapacker
#  get 'IAmACrew', to: 'pages#NovemberIsTheNewCool', as: :iamacrew

  resources :crews, only: [:edit, :update]
  resources :missions, only: [:index, :edit, :update, :new, :show, :create] do
    resources :connections, only: [:new, :create, :edit, :show, :index, :destroy, :update]
  end
  #to change the status of a mission
  get '/missions/:id/validate', to:'missions#validate', as: 'validate_mission'
  get '/missions/:id/suspend', to:'missions#suspend', as: 'suspend_mission'
  get '/missions/:id/close', to:'missions#close', as: 'close_mission'
  get '/missions/:id/cancel', to:'missions#cancel', as: 'cancel_mission'
  #to change the status of a connection
  get '/missions/:mission_id/connections/:id/accept', to:'connections#accept', as: 'accept_connection'
  get '/missions/:mission_id/connections/:id/refuse', to:'connections#refuse', as: 'refuse_connection'
  get '/missions/:mission_id/connections/:id/cancel', to:'connections#cancel', as: 'cancel_connection'
  get '/missions/:mission_id/connections/:id/confirm', to:'connections#confirm', as: 'confirm_connection'
  get '/missions/:mission_id/connections/:id/put_online', to:'connections#put_online', as: 'put_online_connection'
  get '/missions/:mission_id/connections/:id/put_draft', to:'connections#put_draft', as: 'put_draft_connection'
  get '/missions/:mission_id/connections/:id/put_for_admin_validation', to:'connections#put_for_admin_validation', as: 'put_for_admin_validation_connection'

  resources :packers, only: [:edit, :update, :show]


end

app/views/shared/navbar/_authenticated_navbar.html.erb
<div class="navbar_pys">
  <div class="navbar-fixed navbar_sm_md_lg hidden-xs <%= 'transparent' if (controller_name == 'pages' && action_name == 'home') %>">
    <div class='navbar_brand'>
      <%= link_to "Pack Your Skills", authentificated_home_path %>
    </div>
    <div class="navbar_logo">
      <%= link_to image_tag("/home.logo.5cm.png"), root_path %>
    </div>
    <div class="navbar_right">
      <div class="navbar_link">
        <p>Welcome <%= current_user.role.capitalize %><p>
      </div>
      <div class="navbar_button">
        <%= link_to destroy_user_session_path, method: :delete do %>Log Out<% end %>
      </div>
      <% if (controller_name == 'pages' && action_name == 'home') %>
        <div class="navbar_language">
          <% if I18n.locale == I18n.default_locale %>
            <p><u>EN</u> <%= link_to "FR", { :locale=>'fr' } %></p>
          <% else %>
            <p><%= link_to "EN", { :locale=>'' } %><u>FR</u></p>
          <%end%>
        </div>
      <% end %>
    </div>
  </div>


  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar_xs navbar-top hidden-sm hidden-md hidden-lg">
    <div class="navbar_logo">
      <%= link_to image_tag("/home.logo.5cm.png"), root_path %>
    </div>
    <div class='navbar_brand'>
      <%= link_to "Pack Your Skills", authentificated_home_path %>
    </div>
    <div class="navbar_dropdown">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-dropdown-menu">
          <li><%= link_to destroy_user_session_path, method: :delete do %>Log Out<% end %></li>
          <% if (controller_name == 'pages' && action_name == 'home') %>
            <% if I18n.locale == I18n.default_locale %>
              <li><%= link_to "French version", { :locale=>'fr' }%></li>
            <% else %>
              <li><%= link_to "English version", { :locale=>'' }%></li>
            <%end%>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/navbar/_visitor_navbar.html.erb
<div class="navbar_pys">
  <div class="navbar-fixed navbar_sm_md_lg hidden-xs <%= 'transparent' if (controller_name == 'pages' && action_name == 'home') %>">
    <div class='navbar_brand'>
      <%= link_to "Pack Your Skills", root_path %>
    </div>
    <div class="navbar_logo">
      <%= link_to image_tag("/home.logo.5cm.png"), root_path %>
    </div>
    <div class="navbar_right">
      <div class="navbar_link">
        <%= link_to "Sign In", new_user_session_path %>
      </div>
      <div class="navbar_button">
        <%= link_to "Sign Up", new_user_registration_path %>
      </div>
      <% if (controller_name == 'pages' && action_name == 'home') %>
        <div class="navbar_language">
          <% if I18n.locale == I18n.default_locale %>
            <p><u>EN</u> <%= link_to "FR", { :locale=>'fr' } %></p>
          <% else %>
            <p><%= link_to "EN", { :locale=>'' } %> <u>FR</u></p>
          <%end%>
        </div>
      <% end %>
    </div>
  </div>



  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar_xs navbar-top hidden-sm hidden-md hidden-lg">
    <div class="navbar_logo">
      <%= link_to image_tag("/home.logo.5cm.png"), root_path %>
    </div>
    <div class='navbar_brand'>
      <%= link_to "Pack Your Skills", root_path %>
    </div>
    <div class="navbar_button">
      <%= link_to "Sign Up", new_user_registration_path %>
    </div>
    <div class="navbar_dropdown">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-dropdown-menu">
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <% if (controller_name == 'pages' && action_name == 'home') %>
            <% if I18n.locale == I18n.default_locale %>
              <li><%= link_to "French version", { :locale=>'fr' }%></li>
            <% else %>
              <li><%= link_to "English version", { :locale=>'' }%></li>
            <%end%>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>