config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/nelson', as: 'rails_admin'
  mount Attachinary::Engine => "/attachinary"

  devise_for :users,
    controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'}


  authenticated :user do
    root 'pages#room', as: :authenticated_root
    get '/home', to: 'pages#home', as: :authentificated_home
  end

  scope '(:locale)', locale: /fr/ do #to use i18n | change /fr/ to /fr|es/ to add spanish
    root to: 'pages#home'
    get '/home', to: 'pages#home'
    get 'NovemberIsCoolAgain', to: 'pages#NovemberIsCoolAgain', as: :novemberiscoolagain
  end

  get "/CallMaxime" => redirect("https://calendly.com/maximebdb/packyourskills")
  get "/joinourteam" => redirect("http://www.packyourskills.com/RecruitmentJanuary2019.pdf"), as: :joinus

  ## BLOG
  get "/blog", to: redirect('http://blog.packyourskills.com/')
  # get "/blog" => redirect("https://medium.com/pack-your-skills")

  ## temporary #########
  get 'NovemberIsTheNewCool', to: 'pages#NovemberIsCoolAgain', as: :novemberisthenewcool
  get 'fr/NovemberIsTheNewCool', to: 'pages#NovemberIsCoolAgain'
  get 'AprilIsComing', to: 'pages#NovemberIsCoolAgain', as: :apriliscoming
  #######################

  ## temporary #########
#  get 'NovemberIsTheNewCool', to: 'pages#NovemberIsTheNewCool', as: :novemberisthenewcool
#  get 'fr/NovemberIsTheNewCool', to: 'pages#NovemberIsTheNewCool'
  #######################


  get 'IAmAPacker', to: 'pages#IAmAPacker', as: :iamapacker
  get 'IAmACrew', to: 'pages#IAmACrew', as: :iamacrew

#  get 'IAmAPacker', to: 'pages#NovemberIsTheNewCool', as: :iamapacker
#  get 'IAmACrew', to: 'pages#NovemberIsTheNewCool', as: :iamacrew

  resources :crews, only: [:edit, :update]
  resources :missions, only: [:index, :edit, :update, :new, :show, :create] do
    resources :connections, only: [:new, :create, :edit, :show, :index, :destroy, :update]
  end
  #to change the status of a mission
  get '/missions/:id/validate', to:'missions#validate', as: 'validate_mission'
  get '/missions/:id/suspend', to:'missions#suspend', as: 'suspend_mission'
  get '/missions/:id/close', to:'missions#close', as: 'close_mission'
  get '/missions/:id/cancel', to:'missions#cancel', as: 'cancel_mission'
  #to change the status of a connection
  get '/missions/:mission_id/connections/:id/accept', to:'connections#accept', as: 'accept_connection'
  get '/missions/:mission_id/connections/:id/refuse', to:'connections#refuse', as: 'refuse_connection'
  get '/missions/:mission_id/connections/:id/cancel', to:'connections#cancel', as: 'cancel_connection'
  get '/missions/:mission_id/connections/:id/confirm', to:'connections#confirm', as: 'confirm_connection'
  get '/missions/:mission_id/connections/:id/put_online', to:'connections#put_online', as: 'put_online_connection'
  get '/missions/:mission_id/connections/:id/put_draft', to:'connections#put_draft', as: 'put_draft_connection'
  get '/missions/:mission_id/connections/:id/put_for_admin_validation', to:'connections#put_for_admin_validation', as: 'put_for_admin_validation_connection'

  resources :packers, only: [:edit, :update, :show]


end

app/models/mission.rb
class Mission < ApplicationRecord
  belongs_to :crew
  has_many :connections, dependent: :destroy

  geocoded_by :full_address
  after_validation :geocode, if: :full_address_changed?

  has_attachment :cover_mission
  has_attachment :referent_picture
  has_attachment :host_picture
  has_attachment :hosting_place_picture


  def url_cover
    open_constants
    self.cover_mission.nil? ? @constants["img_placeholder_url"][0]  : self.cover_mission.path
  end

  def url_referent_picture
    open_constants
    self.referent_picture.nil? ? @constants["img_placeholder_url"][1] :  self.referent_picture.path
  end

  def url_host_picture
    open_constants
    self.host_picture.nil? ? @constants["img_placeholder_url"][2] :  self.host_picture.path
  end

  def url_hosting_place_picture
    open_constants
    self.hosting_place_picture.nil? ? @constants["img_placeholder_url"][3] :  self.hosting_place_picture.path
  end

  def draft?
    self.status == 'draft'
  end

  def online?
    self.status == 'online'
  end

  def suspended
    self.status = 'suspended'
    self.save
  end

  def suspended?
    self.status == 'suspended'
  end

  def cancel
    self.status = 'canceled'
    self.save
    # self.connections.each do |connection|
    #   connection.cancel
    # end
  end

  def canceled?
    self.status == 'canceled'
  end

  def close
    self.status = 'closed'
    self.save
    # self.connections.each do |connection|
    #   if connection.accepted?
    #   elsif connection.draft?
    #     connection.cancel
    #   else
    #     connection.refuse
    #   end
    # end
  end

  def closed?
    self.status == 'closed'
  end

  def validate
    self.status = 'validated'
    self.save
  end

  def validated?
    self.status == 'validated'
  end

  private

  def open_constants
    @constants = YAML.load_file(Rails.root.join('config', 'constants.yml'))
  end

  def full_address
    self.address.to_s + ', ' + self.city.to_s + ', ' + self.country.to_s
  end

  def full_address_changed?
    address_changed? || city_changed? || country_changed?
  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_crew, only: [ :create, :destroy ]
  before_action :set_mission, only: [ :show, :edit, :update, :validate, :destroy]

  def index
    # selection of the mission
    @all_missions = policy_scope(Mission)
    @online_missions = @all_missions.where(status: 'online')
    @validated_missions = @all_missions.where(status: 'validated')
    @draft_missions = @all_missions.where(status: 'draft')

    @constants = YAML.load_file(Rails.root.join('config', 'constants.yml'))
    @url_cover = @constants["img_banner_url"]["paris"]
  end

  def new
    @mission = Mission.new
    authorize @mission
  end

  def create
    @mission = @crew.missions.build(mission_params)
    params[:commit] == 'Publish' ? (@mission.status = 'online') : (@mission.status = 'draft')
    authorize @mission
    @mission.save ? (redirect_to mission_path @mission) : (render :new)
  end

  def show
    @mission = Mission.find(params[:id])

    @addresses = [@mission, @mission.crew]

    @hash = Gmaps4rails.build_markers(@addresses) do |flat, marker|
      marker.lat flat.latitude
      marker.lng flat.longitude
    end
  end

  def edit
  end

  def update
    params[:commit] == 'Publish' ? (@mission.status = 'online') : (@mission.status = 'draft')
    @mission.update(mission_params) ? (redirect_to mission_path @mission) : (render :edit)
  end

  def validate
    @mission.validate
    redirect_back(fallback_location: authenticated_root_path)
  end

  private

  def set_mission
    @mission = Mission.find(params[:id])
    authorize @mission
  end

  def set_crew
    @crew = Crew.find(current_user.crew)
  end

  def mission_params
    params.require(:mission).permit(:title, :context, :description, :duration, :skill, :material,
    :referent_first_name, :referent_last_name, :referent_role, :referent_phone, :referent_email,
    :host_first_name, :host_last_name, :host_role, :host_phone, :kind_of_hosting,
    :description_hosting_place, :hosting_place_picture, :city, :country, :address, :zip_code,
    :closest_metro_hosting_place, :nb_min_ride, :nb_min_to_center, :other_comment, :status,
    :latitude, :longitude, :cover_mission, :referent_picture, :host_picture)
  end
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/views/missions/_form.html.erb
<%= simple_form_for (@mission) do |a| %>
  <%= a.input :title %>
  <%= a.input :cover_mission, as: :attachinary %>
  <%= a.input :context %>
  <%= a.input :description %>
  <%= a.input :duration %>
  <%= a.input :skill %>
  <%= a.input :material %>

<!-- Referent -->
  <%= a.input :referent_first_name %>
  <%= a.input :referent_last_name %>
  <%= a.input :referent_role %>
  <%= a.input :referent_phone %>
  <%= a.input :referent_email %>
  <%= a.input :referent_picture, as: :attachinary %>

<!-- Host -->
  <%= a.input :host_first_name %>
  <%= a.input :host_last_name %>
  <%= a.input :host_role %>
  <%= a.input :host_phone %>
  <%= a.input :host_picture, as: :attachinary %>

<!-- Hosting place -->
  <%= a.input :description_hosting_place %>
  <%= a.input :hosting_place_picture, as: :attachinary %>

  <p>Address </p>
  <%= a.input :address %>
  <%= a.input :city %>
  <%= a.input :zip_code %>
  <%= a.input :country, as: :string %>
  <%= a.input :closest_metro_hosting_place %>

  <%= a.input :nb_min_ride %>
  <%= a.input :other_comment %>
  <%= a.submit 'Save & keep offline', class: "btn btn-default" if (@mission.status == nil || @mission.status == 'draft' || @mission.status == 'suspended') %>
  <%= a.submit 'Publish', class: "btn btn-primary" %>
<% end %>

app/views/missions/edit.html.erb
<section id="banner" class="banner" >
  <div class="banner_content">
    <h1>MISSION EDIT</h1>
  </div>
</section>
<section id="mission_form" class="form">
  <div class="container_form">
    <%= render 'form' %>
  </div>
</section>

app/views/missions/index.html.erb
<div id="mission_index">
  <section id="banner" class="banner" style="background-image: linear-gradient(rgba(1,1,1,0.5), rgba(1,1,1,0.5)), url('<%= cl_image_path @url_cover %>')" >
    <div class="banner_content">
      <h1><%= t('mission.index.title') %></h1>
      <h2><%= t('mission.index.subtitle') %></h2>
    </div>
  </section>

  <section id="introduction" class="section_blue" >
    <div class="introduction_container">
      <p><%= t('mission.index.introduction.intro1') %></p>
      <p><%= t('mission.index.introduction.intro2') %></p>
      <h2><%= t('mission.index.introduction.hashtag') %></h2>
      <p><%= t('mission.index.introduction.explication') %></p>
      <p><%= t('mission.index.introduction.call2action') %></p>
    </div>
  </section>
<!--
  <section id="mission_teasing_call2action" class="section">
    <div class="container">
      <div class="row">
        <div class='col-xs-12 col-md-6'>
          <div class="row">
            <div class='col-xs-12 col-sm-3 hide_for_phone arrow arrow_right '>
              <%= image_tag "/home.packers.png" %>
            </div>
            <div class='col-xd-12 col-sm-9'>
              <p><strong><%= t('nov2018.call2action.packers.name') %></strong></p>
              <p><%= t('nov2018.call2action.packers.text') %></p>
              <p class="comment"><strong><%= t('nov2018.call2action.packers.comment') %></strong></p>
              <%= link_to t('nov2018.call2action.packers.call2action'), new_user_registration_path, class: "green_call2action" %>
            </div>
          </div>
        </div>
        <div class='col-xs-12 col-md-6'>
          <div class="row">
            <div class='col-xs-12 col-sm-3 hide_for_phone arrow arrow_left'>
              <%= image_tag "/home.crews.png" %>
            </div>
            <div class='col-xd-12 col-sm-9'>
              <p><strong><%= t('nov2018.call2action.crews.name') %></strong></p>
              <p><%= t('nov2018.call2action.crews.text') %></p>
              <p class="comment"><strong><%= t('nov2018.call2action.crews.comment') %></strong></p>
              <a class="green_call2action" href="http://bit.ly/PYS_NOV18" role="button"><%= t('nov2018.call2action.crews.call2action') %></a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="old_mission" class="section_red" >
      <div class="introduction_container">
        <p><%= t('mission.index.oldmission.title') %></p>
      </div>
    </div>
  </section>
 -->

  <section class="main-container">
    <div class="container">
      <div class="row">
        <div class="main col-md-12">
          <!-- isotope filters start -->
          <div class="filters">
            <ul class="nav nav-pills">
              <li class="active"><a href="#" data-filter="*"><%= t('mission.index.filter.all') %></a></li>
              <li><a href="#" data-filter=".graphicdesign"><%= t('mission.index.filter.graphic') %></a></li>
              <li><a href="#" data-filter=".video"><%= t('mission.index.filter.video') %></a></li>
              <li><a href="#" data-filter=".webdevelopment"><%= t('mission.index.filter.webdev') %></a></li>
              <li><a href="#" data-filter=".webmarketing"><%= t('mission.index.filter.webmarket') %></a></li>
            </ul>
          </div>
          <!-- isotope filters end -->
          <div class="isotope-container">
            <% @online_missions.each_with_index do |mission, index| %>
              <div class="col-xs-12 col-sm-6 col-md-4 isotope-item <%= mission.skill.downcase.gsub(/\s+/, "") %>">
                <div class= "card_mission">
                  <div class= "banner_card_mission" style="background-image: url('<%= cl_image_path mission.url_cover, angle: 0 %>')" >
                    <div class= "box box_ratio_1_1" style="background-image: url('<%= cl_image_path mission.crew.url_logo, angle: 0 %>')" >
                    </div>
                  </div>
                  <div class= "info_card_mission">
                    <p><%= mission.crew.name %></p>
                    <p><strong><%= mission.title %></strong></p>
                    <p>#<%= mission.skill %></p>
                    <p>#<%= mission.crew.cause %></p>
                  </div>
                  <%= link_to "", mission_path(mission.id) %>
                </div>
              </div>
            <% end %>

<!--
             <% @validated_missions.each_with_index do |mission, index| %>
              <div class="col-xs-12 col-sm-6 col-md-4 isotope-item <%= mission.skill.downcase.gsub(/\s+/, "") %>">
                <div class= "card_mission">
                  <div class= "banner_card_mission" style="background-image: url('<%= cl_image_path mission.url_cover, angle: 0 %>')" >
                    <div class= "box box_ratio_1_1" style="background-image: url('<%= cl_image_path mission.crew.url_logo, angle: 0 %>')" >
                    </div>
                  </div>
                  <div class= "info_card_mission">
                    <p><%= mission.crew.name %></p>
                    <p><strong><%= mission.title %></strong></p>
                    <p>#<%= mission.skill %></p>
                    <p>#<%= mission.crew.cause %></p>
                  </div>
                  <div class="validated_mission">
                    <div class="content">
                      <p>They already found their Packer</p>
                    </div>
                  </div>
                  <%= link_to "", mission_path(mission.id) %>
                </div>
              </div>
            <% end %>
 -->

          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/missions/new.html.erb
<section id="banner" class="banner" style="background-image: linear-gradient(rgba(1,1,1,0.5), rgba(1,1,1,0.5)), url('<%= @url_cover %>')" >
  <div class="banner_content">
    <h1>NEW MISSION</h1>
  </div>
</section>
<section id="mission_form" class="form">
  <div class="container_form">
    <%= render 'form' %>
  </div>
</section>

app/views/missions/show.html.erb
<div id="mission_show" class="global_show">

<!-- Banner Part -->
  <section id="banner_packer" class="banner" style="background-image: linear-gradient(rgba(138,215,218,0.5), rgba(138,215,218,0.5)), url('<%= cl_image_path @mission.url_cover, angle: 0 %>')" >
    <div class="banner_content">
      <h1><%= @mission.title %></h1>
    </div>
  </section>

<!-- Second Navbar Part -->
  <section id="mission_show_navbar" class='secondary_navbar section_gray'>
    <div class="nav_bar_items">
      <%= link_to t('mission.show.crew.section_title'), '#crew_mission_show' %>
    </div>
    <div class="nav_bar_items">
      <%= link_to t('mission.show.crew.mission'), '#mission_mission_show' %>
    </div>
    <div class="nav_bar_items">
      <%= link_to t('mission.show.workplace.section_title'), '#workplace_mission_show' %>
    </div>
    <div class="nav_bar_items">
      <%= link_to t('mission.show.team.section_title'), '#team_mission_show' %>
    </div>
    <div class="nav_bar_items">
      <%= link_to t('mission.show.host.section_title'), '#host_mission_show' %>
    </div>
    <% if @mission.status == 'online' %>
      <div class="nav_bar_items call2action">
        <%= link_to t('mission.show.apply'), new_mission_connection_path(@mission.id) %>
      </div>
    <% end %>
  </section>

  <% unless @mission.status == 'online' %>
    <section id="message_mission_not_online" class="section_red">
      <% case @mission.status %>
      <% when 'validated' %>
        <p>This opportunity already found a Packer, so you cannot apply anymore =>
        <strong><%= link_to "see all the other opportunities", missions_path %></strong></p>
      <% else %>
        <p><%= @mission.status %></p>
      <% end %>
    </section>
  <% end %>

<!-- crew_mission_show Part -->
  <section id="summary_mission_show" class="summary_global_show section_blue">
    <div class='logo'>
      <div class='box box_ratio_1_1' style="background-image: url('<%= cl_image_path @mission.crew.url_logo, angle: 0 %>')">
      </div>
    </div>
    <div class='social_media'>
      <ul class="social-icon-list list-unstyled">
        <% if @mission.crew.facebook != (nil || '') %><li>
          <%= link_to "", @mission.crew.facebook, target: "_blank", class: "fa fa-facebook" %>
        </li><% end %>
        <% if @mission.crew.twitter != (nil || '') %><li>
          <%= link_to "", @mission.crew.twitter, target: "_blank", class: "fa fa-twitter" %>
        </li><% end %>
        <% if @mission.crew.instagram != (nil || '') %><li>
          <%= link_to "", @mission.crew.instagram, target: "_blank", class: "fa fa-instagram" %>
        </li><% end %>
        <% if @mission.crew.website != (nil || '') %><li>
          <%= link_to "", @mission.crew.website, target: "_blank", class: "fa fa-globe" %>
        </li><% end %>
    </div>
    <div class='information'>
      <p><strong><%= @mission.crew.name %></strong></p>
      <p><%= t('mission.show.summary.created') %><%= @mission.crew.creation_date %></p>
      <p>#<%= @mission.skill.capitalize %></p>
      <p>#<%= @mission.city %></p>
      <p><%= @mission.duration %> days - November 5-19,2017</p>
    </div>
  </section>

<!-- crew_mission_show Part -->
  <section id="crew_mission_show" class="section section_path section_right_path section_yellow1_left">
    <div class='container'>
      <h2><%= t('mission.show.crew.title') %></h2>
      <p><%= @mission.crew.mission %></p>
      <p><strong><%= t('mission.show.crew.what') %></strong></p>
      <p><%= @mission.crew.description %></p>
    </div>
  </section>

<!-- mission_mission_show Part -->
  <section id="mission_mission_show" class="section section_path section_left_path section_red1_right">
    <div class='container'>
      <h2><%= t('mission.show.mission.title') %></h2>
      <p><%= @mission.context %></p>
      <p><%= @mission.description %></p>
      <p><u><%= t('mission.show.mission.equipment') %></u><br><%= @mission.material %></p>

    </div>
  </section>

<!-- workplace_mission_show Part -->
  <section id="workplace_mission_show" class="section section_path section_right_path section_blue1_left">
    <div class='container'>
      <h2><%= t('mission.show.workplace.title') %></h2>
      <p><%= @mission.crew.description_working_place %></p>
      <%= cl_image_tag @mission.crew.url_working_place_picture, angle: 0 %>
    </div>
  </section>

<!-- team_mission_show Part -->
  <section id="team_mission_show" class="section section_green2_right">
    <div class='container'>
      <div class='row'>
        <h2><%= t('mission.show.team.title') %></h2>
        <%= cl_image_tag @mission.crew.url_team_picture, angle: 0 %>
      </div>
      <div class='row'>
        <table>
          <tr>
            <th><p><%= @mission.crew.nb_collaborators %> <%= t('mission.show.team.nb_people') %></p></th>
            <th><p><%= @mission.crew.average_age %> <%= t('mission.show.team.average_age') %></p></th>
          </tr>
          <tr>
            <th><p><%= @mission.crew.percentage_women %>% <i class="fa fa-female" aria-hidden="true"></i> <%= (100 - @mission.crew.percentage_women) %>% <i class="fa fa-male" aria-hidden="true"></i></p></th>
            <th><p><%= @mission.crew.percentage_english %>% <%= t('mission.show.team.percentage_en') %></p></th>
          </tr>
        </table>
      </div>
      <div class='row'>
        <p><%= @mission.crew.team_description %></p>
      </div>
      <div class='row referent_and_host'>
        <div class='portrait'>
          <div class="avatar" style="background-image: url('<%= cl_image_path @mission.url_referent_picture, gravity: :face, angle: 0 %>')" >
          </div>
        </div>
        <div class='info'>
          <p><strong><%= @mission.referent_first_name %> <%= @mission.referent_last_name %></strong></p>
          <p><%= @mission.referent_role %></p>
        </div>
      </div>
    </div>
  </section>

<!-- Values Part -->
  <section id="value_mission_show" class="section section_path section_left_path value_global_show">
    <div class="section_yellow">
      <div class='container'>
        <h2><%= t('mission.show.values.title') %></h2>
        <p><%= t('mission.show.values.why_html') %></p>
        <ul>
          <% if @mission.crew.value1 != (nil || '') %>
            <li><p><%= @mission.crew.value1 %></p></li>
          <% end %>
          <% if @mission.crew.value2 != (nil || '') %>
            <li><p><%= @mission.crew.value2 %></p></li>
          <% end %>
          <% if @mission.crew.value3 != (nil || '') %>
            <li><p><%= @mission.crew.value3 %></p></li>
          <% end %>
        </ul>
      </div>
    </div>
  </section>

<!-- host_mission_show Part -->
  <section id="host_mission_show" class="section section_red2_left">
    <div class='container'>
      <div class='row'>
        <h2><%= t('mission.show.host.title') %></h2>
      </div>
      <div class='row referent_and_host'>
        <div class='portrait'>
          <div class="avatar" style="background-image: url('<%= cl_image_path @mission.url_host_picture, gravity: :face, angle: 0 %>')" >
          </div>
        </div>
        <div class='info'>
          <p><strong><%= @mission.host_first_name %> <%= @mission.host_last_name %></strong></p>
          <p><%= @mission.host_role %></p>
        </div>
      </div>
      <div class='row'>
        <p><%= @mission.description_hosting_place %></p>
      </div>
      <div class='row'>
        <table>
          <tr>
            <th><p><%= @mission.kind_of_hosting %></p></th>
            <th><p><%= t('mission.show.host.distance_paris') %><%= @mission.nb_min_to_center %></p></th>
          </tr>
          <tr>
            <th><p><%= t('mission.show.host.distance_workplace') %><%= @mission.nb_min_ride %></p></th>
            <th><p><%= t('mission.show.host.close_subway') %> <%= @mission.closest_metro_hosting_place %></p></th>
          </tr>
        </table>
      </div>
      <div class='row'>
        <div class="col-xs-12 col-sm-6">
          <div class="box_ratio_2_3 hosting_place_picture" style="background-image: url('<%= cl_image_path @mission.url_hosting_place_picture, angle: 0 %>')" >
          </div>>
        </div>
        <div class="col-xs-12 col-sm-6">
          <div class="box_ratio_2_3">
            <div class="content_box">
              <div id="map">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
<!-- Values Part -->
  <% if @mission.status == 'online' %>
    <section class="call2action">
      <%= link_to t('mission.show.apply'), new_mission_connection_path(@mission.id), class: "btn btn-primary btn-lg" %>
    </section>
  <% end %>
</div>



<% content_for(:after_js) do %>
  <script>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  </script>
<% end %>